# Generated by Django 2.2.19 on 2024-06-22 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240622_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 22, 2, 24, 6, 155646, tzinfo=utc)),
        ),
    ]
